=== psehgaft/Microservicios/FlightMonitor_WSDL_SOAP/build/META-INF/boardList.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://pad.polito.it/boardList" xmlns:tns="http://pad.polito.it/boardList">


    <element name="boardList" type="tns:boardListType"></element>
    
    <complexType name="boardListType">
        <annotation>
        	<documentation>The list of boarded passengers for a flight instance</documentation></annotation>
        <sequence>
    		<element name="passenger" type="tns:passengerType"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    	</sequence>
    	<attribute name="flight" type="string">
    		<annotation>
    			<documentation>the flight number of this board list</documentation>
    		</annotation>
    	</attribute>
    	<attribute name="date" type="date">
    		<annotation>
    			<documentation>the date of the flight of this board list</documentation>
    		</annotation>
    	</attribute>
    </complexType>

    <complexType name="passengerType">
        <annotation>
        	<documentation>A boarded passenger</documentation>
        </annotation>
        <simpleContent>
    		<extension base="string">
    			<attribute name="seat" type="string">
    				<annotation>
    					<documentation>The seat assigned to the passenger</documentation>
    				</annotation>
    			</attribute>
    		</extension>
    	</simpleContent>
    </complexType>
</schema>

=== psehgaft/Microservicios/FlightMonitor_WSDL_SOAP/test.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:boardList xmlns:ns2="http://pad.polito.it/boardList" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" flight="HC890" date="2010-02-15+01:00" xsi:schemaLocation="./xsd/boardList.xsd">
    <passenger seat="9D">Clara Aziz</passenger>
    <passenger seat="1D">Paola Aziz</passenger>
    <passenger seat="14D">Giuseppe Aziz</passenger>
    <passenger seat="10C">Mario Turturro</passenger>
    <passenger seat="9C">Giovanni Rossi</passenger>
    <passenger seat="4B">Francesca Diana</passenger>
    <passenger seat="5A">Ludovico Gonzales</passenger>
    <passenger seat="2A">Elisabeth Di Crescenzo</passenger>
    <passenger seat="3B">Carlo Rossi</passenger>
    <passenger seat="7C">Elisabeth Servini</passenger>
    <passenger seat="3C">Giovanni Piccoli</passenger>
    <passenger seat="11C">Marta Diana</passenger>
    <passenger seat="1C">Marco Rossi</passenger>
    <passenger seat="13B">Giuseppe Bianchi</passenger>
    <passenger seat="7D">Clara Elkan</passenger>
    <passenger seat="15A">Francesca Perissino</passenger>
    <passenger seat="13C">Sonia Del Santo</passenger>
</ns2:boardList>

=== psehgaft/Microservicios/FlightMonitor_WSDL_SOAP/risultatoIVOnuovo.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:boardList xmlns:ns2="http://pad.polito.it/boardList" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" flight="MA665" date="2010-02-14+01:00" xsi:schemaLocation="./xsd/boardList.xsd">
    <passenger seat="13D">Paolo Aziz</passenger>
    <passenger seat="9B">Claude Bianchi</passenger>
    <passenger seat="26A">Paola Baldo</passenger>
    <passenger seat="22D">John Elkan</passenger>
    <passenger seat="23D">Carlo Baldo</passenger>
    <passenger seat="16A">Caio Perissino</passenger>
    <passenger seat="10A">Mauro Perissino</passenger>
    <passenger seat="19B">Caio Turturro</passenger>
    <passenger seat="7B">Giuseppe Aziz</passenger>
    <passenger seat="11C">Giuseppe Chemin</passenger>
    <passenger seat="14B">Francesco Del Santo</passenger>
    <passenger seat="14C">Clara Aziz</passenger>
    <passenger seat="24C">Marco Del Santo</passenger>
    <passenger seat="21B">Claude Piccoli</passenger>
    <passenger seat="12B">Paolo Del Santo</passenger>
    <passenger seat="15A">Giovanni Aziz</passenger>
    <passenger seat="22C">Paolo Rossi</passenger>
    <passenger seat="1A">Elisabeth Di Crescenzo</passenger>
    <passenger seat="13B">Diana Bianchi</passenger>
</ns2:boardList>

=== psehgaft/Microservicios/FlightMonitor_WSDL_SOAP/risultatoIVO.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:boardList xmlns:ns2="http://pad.polito.it/boardList" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" flight="HY903" date="2010-02-15+01:00" xsi:schemaLocation="./xsd/boardList.xsd">
    <passenger seat="3D">Marco Chemin</passenger>
    <passenger>Marta Bianchi</passenger>
    <passenger seat="15D">Francesco Gonzales</passenger>
    <passenger seat="6A">Mario Piccoli</passenger>
    <passenger>Carlo Perissino</passenger>
    <passenger seat="11A">Ludovico Turturro</passenger>
    <passenger seat="10A">Monica Elkan</passenger>
    <passenger seat="1B">Francesca Aziz</passenger>
    <passenger>Elisabeth Diana</passenger>
    <passenger seat="1A">Monica Bianchi</passenger>
    <passenger>Claude Baldo</passenger>
    <passenger seat="15A">Maurizio Baldo</passenger>
    <passenger seat="5C">Claude Chemin</passenger>
    <passenger>Eva Perissino</passenger>
    <passenger seat="11B">Elisabeth Bianchi</passenger>
    <passenger>Marco Piccoli</passenger>
    <passenger>Anna Baldo</passenger>
    <passenger>Carlo Di Crescenzo</passenger>
    <passenger>Monica Baldo</passenger>
    <passenger seat="4D">Caio Perissino</passenger>
    <passenger seat="9B">Claudio Gonzales</passenger>
    <passenger>Marco Bianchi</passenger>
    <passenger seat="5A">Giuseppe Baldo</passenger>
    <passenger seat="5B">Francesca Servini</passenger>
    <passenger seat="8B">Sonia Gonzales</passenger>
    <passenger seat="12B">Marta Chemin</passenger>
    <passenger>Andrea Diana</passenger>
    <passenger>Andrea Bianchi</passenger>
    <passenger>Giuseppe Bianchi</passenger>
    <passenger>Giuseppe Aziz</passenger>
    <passenger>Pippo Piccoli</passenger>
    <passenger seat="3A">Elisabeth Turturro</passenger>
    <passenger seat="1D">Claude Diana</passenger>
    <passenger seat="12A">Mario Servini</passenger>
    <passenger>Mario Diana</passenger>
    <passenger>Elisabeth Gonzales</passenger>
    <passenger seat="3C">Mario Rossi</passenger>
    <passenger seat="4C">Paolo Baldo</passenger>
    <passenger seat="2D">Matteo Di Crescenzo</passenger>
    <passenger seat="14D">Maurizio Del Santo</passenger>
    <passenger seat="12C">Francesco Piccoli</passenger>
    <passenger>Andrea Del Santo</passenger>
    <passenger seat="6D">Francesco Chemin</passenger>
    <passenger>Carlo Turturro</passenger>
    <passenger>Paola Perissino</passenger>
    <passenger>Carol Elkan</passenger>
    <passenger seat="9A">Carol Servini</passenger>
    <passenger seat="6C">Carol Perissino</passenger>
    <passenger seat="13B">Carlo Piccoli</passenger>
    <passenger seat="7C">Claudio Perissino</passenger>
    <passenger>Clara Turturro</passenger>
    <passenger seat="9D">Mauro Piccoli</passenger>
</ns2:boardList>
